slogan: ã€Œè†å¬æ–°æ€æƒ³ è§£æ”¾æ—§é“å¾·ã€
email: modnarshen@gmail.com
logo: "/images/logo.svg"

mathjax: false # åŠ è½½ LateX æ•°å­¦å…¬å¼åº“

favicon: # é…ç½®ç½‘é¡µå›¾æ ‡
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg

subpage: # å¼€å¯â€œå­é¡µâ€åŠŸèƒ½ï¼Œè¯¦è§ README
  enable: true
  pages:
    # - name: blog # æ–‡ç« çš„åˆ†ç±»ï¼ˆcategoryï¼‰åï¼Œå¦‚ developer
    #   path: # è‹¥ä¸è®¾ç½®åˆ™é»˜è®¤ä½¿ç”¨ name
    #   title: å…¶ä»– # èœå•åï¼Œå¦‚ å¼€å‘è€…
    #   icon: /images/icon/icon-pi.svg # å›¾æ ‡çš„è·¯å¾„
    #   description: # æè¿°
    - name: articles
      path: 
      title: å†™ä½œ
      icon: /images/icon/icon-blog.svg 
      description:
    - name: discussion
      path:
      title: è®¨è®º
      icon: /images/icon/icon-email.svg
      description:
    - name: gallery
      path:
      title: å“å‘³
      icon: /images/icon/icon-book.svg
      description:

index: # é…ç½®é¦–é¡µä¸ªæ€§åŒ–å†…å®¹
  motto: "åº”æ— æ‰€ä½ è€Œç”Ÿå…¶å¿ƒ"
  poem:
    - å›ä¸è§é«˜å ‚æ˜é•œæ‚²ç™½å‘
    - æœå¦‚é’ä¸æš®æˆé›ª
  photo: /images/modoo.jpeg
  about:
    title: æ¬¢è¿
    text:
      - ä½ å¥½ï¼Œæˆ‘æ˜¯ã€Œè«å¤šã€ï¼Œ
      - æ¥è‡ªèŒ«èŒ«æ˜Ÿè¾°å®‡å®™ä¸­å¦ä¸€æ—¶ç©ºçš„æœ‹å‹ã€‚
      - æ¬¢è¿è®¿é—® ğ™ˆğ™¤ğ™™ğ™¤ğ™¤ğ™•ğ™¤ğ™£ğ™šï¼Œ
      - æ„¿ä½ åœ¨æ„Ÿæ…¨ç°å®ä¸‡åƒä¹‹åï¼Œ
      - ä¾æ—§ä¿ç•™ä¸€æ–¹ç†æƒ³ä¸»ä¹‰ç©ºé—´ã€‚
      - åœ¨è¿™é‡Œï¼Œæˆ‘ä»¬ä¸€èµ·èŠèŠå½¼æ­¤çš„æ•…äº‹ã€‚
      - å¸¦ç€å¯èƒ½ç”±æ­¤å……ç›ˆçš„å‹‡æ°”å’Œæ™ºæ…§ï¼Œå†å‡ºå‘ã€‚

foot:
  title:
    - "æµ·å†…å­˜çŸ¥å·±"
    - "å¤©æ¶¯è‹¥æ¯”é‚»"

links: # æœ‹å‹
  - name: "LLVM"
    url: https://llvm.org/

social: # è´¦å·
  - name: "github"
    icon: "/images/logo-github.svg"
    url: https://github.com/Modnars
  # - name: "å¾®ä¿¡å…¬ä¼—å·"
  #   icon: "/images/logo-wx.svg"
  #   url: https://mp.weixin.qq.com/s?__biz=MzI3NzQ4NDkzNg==&mid=2247484469&idx=1&sn=8a442bb67397f52cce5c38c3f9b41e36&chksm=eb64c0d2dc1349c40d2e1bb55615ae28b3f2951be22f00717b9ade98c851082e42dc666ab45d#rd
  # - name: "çŸ¥ä¹"
  #   icon: "/images/logo-zh.svg"
  #   url: https://www.zhihu.com/

reward: # èµèµ
  enable: false
  face: # å¤´åƒå›¾ç‰‡
  paycode: # æ”¯ä»˜ç å›¾ç‰‡
  text: â€œè¯·ä½œè€…å–æ¯å’–å•¡â€
  btnText: å–œæ¬¢ä½œè€…

# see https://github.com/gitalk/gitalk
gitalk: # gitalk è¯„è®º
  enable: false
  owner: # MUST HAVE, Your Github Username
  admin:
  repo: # MUST HAVE, The name of the repo you use to store Gitment comments
  clientID: # MUST HAVE, Github client id for the Gitment
  clientSecret: # EITHER this or proxy_gateway, Github access secret token for the Gitment

  distractionFreeMode: false # Facebook-like distraction free mode
  # When the official proxy is not available, you can change it to your own proxy address
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token # This is official proxy adress
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available values: en | es-ES | fr | ru | zh-CN | zh-TW
  language: zh-CN

# see https://github.com/tea3/hexo-related-popular-posts
related_post:
  enable: false
  config:
    maxCount: 5 # Maximum count of a list. default 5
    ulClass: # Class name of element. deafult 'popular-posts'
    PPMixingRate: 0.4 # Mixing ratio of popular posts and related posts. default 0.0(=Related posts only)
    isDate: # visible the date. false
    isImage: # visible the image. false
    isExcerpt: # visible the excerpt. false
    PPCategoryFilter: # Option to fix category on Popular Posts. undefined
    PPTagFilter: # Option to fix tag on Popular Posts. undefined

# Baidu Webmaster tools verification.
# See: https://ziyuan.baidu.com/site
baidu_site_verification:

# Baidu Analytics
# See: https://tongji.baidu.com
baidu_analytics: # <app_id>

# è‡ªå®šä¹‰å­—ä½“ï¼Œç”¨äºç¾åŒ–éƒ¨åˆ†æ±‰å­—çš„æ˜¾ç¤ºæ•ˆæœ.
# å¯ä»¥é€šè¿‡æ›¿æ¢ _font/ ç›®å½•ä¸‹çš„å­—ä½“æ–‡ä»¶æ›¿æ¢è‡ªå·±å–œæ¬¢çš„å­—ä½“
zh_font:
  enable: true
  fontName: 'SourceHanSerif'
  type: ttf
  style:
    - regular
    - bold

# é…ç½®æ—¶é—´çº¿ å‚è€ƒ README.md
timeline:
  enable: true
  order: false # æ˜¯å¦æŒ‰æ—¶é—´æ­£åºå±•ç¤ºï¼Œfalse ä¸ºå€’åº
  items:
    - name: event
      color: "#568DC4"
      icon: /images/icon/icon-event.svg
      checked: true
    - name: slogan
      color: "#60A465"
      icon: /images/icon/icon-sunrise.svg
      checked: true
    - name: reading
      color: "#F9AB02"
      icon: /images/icon/icon-book.svg
      checked: false
    - name: discussion
      color: "#EE936C"
      icon: /images/icon/icon-article.svg
      checked: false

# æ ‡ç­¾äº‘
tagcloud:
  fancy: true
  min_font: 14
  max_font: 30
